using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Gasolin.Model;

namespace Gasolin.Pages;

public class IndexModel : PageModel
{
    // slet??? private readonly ILogger<IndexModel> _logger;

    public Member[] members = new Member[5];

    /* slet ??? public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }*/

    public void OnGet()
    {
        members[0] = new Member("Kim Larsen", "pictures/kim-larsen.jpg", "Forsanger, Guitarist", 1945, 2018, "KimLarsen");
        members[1] = new Member("Franz Beckerlee", "pictures/nyfranz-beckerlee.jpg", "Guitarist", 1942, 0, "FranzBeckerlee");
        members[2] = new Member("Wili Jønsson", "pictures/wili-jønsson.jpg", "Bassist", 1942, 0, "WiliJønsson");
        members[3] = new Member("Bjørn Uglebjerg", "pictures/bjørn-uglebjerg.jpg", "Trommeslager", 1948, 1994, "BjørnUglebjerg");
        members[4] = new Member("Søren Berlev", "pictures/nysoeren-berlev.jpg", "Trommeslager", 1950, 0, "SørenBerlev");

        members[0].Bio = "Kim Mellius Flyvholm Larsen (født 23. oktober 1945 i København, død 30. september 2018 i Odense) var en dansk sanger, sangskriver, folkeskolelærer, forfatter og guitarist. Han begyndte sin musikalske karriere i 1968 efter en kort periode som folkeskolelærer og blev fra 1969 kendt som medlem af rockgruppen Gasolin. I sin tid med Gasolin (varede indtil 1978) udgav Larsen dog også såvel soloplader og plader med sit fritidsband, der blev kendt under flere navne, og efter Gasolins opløsning fortsatte Larsen som solist og bandleder.\r\n\r\nHan var fra 1970'erne en af Danmarks mest populære musikere og omtaltes ofte som \"Danmarks nationalskjald\", selv foretrak han dog blot at være \"spillemand\".\r\n\r\nHan forsøgte sig i starten af 1980'erne med et gennembrud i USA, og da dette ikke lykkedes, vendte han hjem til Danmark, hvor han blev medforfatter på filmen Midt om Natten, havde den ene af hovedrollerne, en præstation han blev anerkendt med en Robert for, og skrev og indspillede det meste af musikken til filmen.\r\n\r\nFra 1980'erne og frem indgik Kim Larsen i forskellige bands og grupper. I 1980'erne Kim Larsen & Bellami, i en periode af 1990'erne Kim Larsen & Bell*Star og fra midten af 1990'erne og i mere end tyve år frem til Larsens død Kim Larsen & Kjukken.\r\n\r\nHan skrev ikke kun sange til eget brug, men også adskillige sange, som andre kunstnere fremførte, ligesom Larsen også kom med sine egne fortolkninger af danske og udenlandske evergreens og melodier samt en række af de mest populære danske salmer.\r\n\r\nSom solist solgte han flere end tre millioner plader og samlet set over fem millioner eksemplarer.";
        members[1].Bio = "Franz Beckerlee (født 15. august 1942) er en dansk musiker, der var guitarist i rockgruppen Gasolin. Han har desuden spillet jazz.\r\n\r\nBeckerlee spiller guitar og saxofon. Han begyndte at spille saxofon som 12-årig. Sammen med Hugh Steinmetz, Niels Harrit, Steffen Andersen og Bo Thrige Andersen dannede han The Contemporary Jazz Quintet, som spillede avantgardejazz. Kvintetten fik megen ros af kritikere og presse, men fik ingen større succes hos publikum. Franz fik tildelt årets jazzlegat i 1964 og 1968. Derefter kom Franz Beckerlee med i Gasolin', hvor han spiller guitar a la Jimi Hendrix. Efter Gasolin' var Franz Beckerlee med i Christianshavns Bluesband sammen med Søren Berlev og Lone Kellermann. ";
        members[2].Bio = "Wili Jønsson (født 27. marts 1942 på Amager) er dansk bassist, keyboardspiller og korsanger, der især er kendt for tiden som bassist med Gasolin', hvor han af især Kim Larsen blev kaldt \"den skeløjede halvsvensker\". Han har også spillet i mange andre konstellationer, blandt andet med Sort Sol (band), Sanne Salomonsen og med Peter Belli. Modtog i 2008 Ken Gudman Prisen for sin fem årtier lange musiske karriere. I 2009 deltog Wili Jønsson i TV2 programmet Allstars, som en del af kollegaen – tidligere forsanger fra Sort Sol – Steen Jørgensens kor. ";
        members[3].Bio = "Bjørn Uglebjerg (21. marts 1948 i København – 21. juni 1994) var en dansk trommeslager.\r\n\r\nSom 15-årig i 1963 dannede Bjørn Uglebjerg sammen med Peer Frost gruppen The Foottappers som senere blev til Les Rivals. Uglebjerg var første trommeslager i Gasolin'. I 1971 blev han udskiftet med Søren Berlev, og medvirkede senere som trommeslager og percussionist på Skousen & Ingemanns Herfra hvor vi står (1971) og Lone Kellermann og Rockbandets Før Natten Bli'r til dag (1978) og Tilfældigt Forbi (1979). Desuden var Uglebjerg fast medlem af Frede Norbrinks gruppe Frede Fup.\r\n\r\nUglebjerg var en flittigt benyttet studiemusiker og trommeslager i diverse konstellationer. Han var meget aktiv musikpolitisk herhjemme, og var en vellidt person i musiske kredse.[kilde mangler]\r\n\r\nHan dannede privat par med Susanne Mertz, som var en af grundene til han forlod Gasolin' i 1971. Han valgte at tilbringe tiden med hende, frem for de store tiltagende diskussioner som prægede bandet dengang. Susanne Mertz, datter af kunstmaler Albert Mertz, var og er stadigvæk fotograf, hvorfor mange af Bjørns koncerter er foreviget af Susanne Mertz.\r\n\r\nFrem mod sin død spillede han flittigt i bandet \"All Stars\", som var et band der blev dannet som husorkester til en programrække i tv. I \"All Stars\" var der også så prominente musikere som Billy Cross, Flemming Ostermann og Jens Rugsted. Tv-udsendelserne gav efterfølgende bandet en masse livejobs.\r\n\r\nBjørn Uglebjerg bosatte sig de sidste år af sit liv i Svendborg, og var også her meget aktiv i musikforeningslivet. ";
        members[4].Bio = "Søren \"Charlie\" Berlev (født 4. maj 1950 i Skt. Nikolai sogn, Nakskov) er en dansk musiker, der blev kendt som trommeslager i Gasolin'. Før Gasolin medlem af Dig og mig og solskin fra 1967-1969. Siden har han blandt andet være medlem af bandet Midnight Blues.\r\n\r\nSøren Berlev er søn af cand.mag. Finn Berlev (fra 1961 lektor i fysik og matematik på Jonstrup Statsseminarium) og hustru Kirsten Marie Bahnson. Søren Berlev er ikke døbt.\r\n\r\nSom 19-årig rejste Søren hjemmefra og ind til slumstormermiljøet på Nørrebro i København. Han blaffede i 1970 til Thylejren, hvor han for første gang hørte Gasolin'.\r\n\r\nEfter Gasolin's opløsning i 1978 flyttede Søren Berlev til USA og boede der til 1984, hvor han i perioden indgik i forskellige bands, blandt andet rock/reggae-trioen Wild Remain der udsendte en enkelt single på CBS i 1980, og også turnerede i Danmark.\r\n\r\nI 1989 var han en del af den gendannede gruppe The Lollipops, der nåede at udsende et enkelt album inden de gik fra hinanden igen.\r\n\r\nFra 1987 til 1992 spillede han desuden i Christianshavns Bluesband med blandt andre Franz Beckerlee, Lone Kellermann, Sten Haxø, Peter Mandorf m.fl. Bandet var flittig turnerende og fejrede store triumfer på landets livescener, hvor de blandt andet spillede på både Midtfyns Festival og Skanderborg Festival og desuden også turnerede på Færøerne.\r\n\r\nI 1997-98 spillede Berlev i bandet Superhead, til hvilket han også bidrog som sangskriver.\r\n\r\nHan blev i år 2000 trommeslager i syretrioen Dream City med guitaristen TømrerClaus og bassisten og sangeren Peter Ingemann.\r\n\r\nI 2007 påbegyndte Søren Berlev arbejdet med en soloplade, med planlagt udgivelse i foråret 2008, på Sony Music. Resultatet forelå i marts 2008 med cd'en Timeless Choice.\r\n\r\nSøren Berlev blev senere trommeslager i det gendannede Young Flowers med Peer Frost og Peter Ingemann. Han dannede i 10'erne også bandet Berlev's Rock 'N' Roll Hotel, der udsendte pladerne You Can Make It (2018) og Close To The Line (2019). ";
    }
}
